//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermeAvicole
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        public int Card_Id { get; set; }
        public int User_Id { get; set; }
        public string Card_HolderName { get; set; }
        public string Expire_Date { get; set; }
        public string Card_Number { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
