//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermeAvicole
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorReport
    {
        public int DoctorReport_Id { get; set; }
        public int Doctor_Id { get; set; }
        public System.DateTime Report_Date { get; set; }
        public string File_Path { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public int User_Id { get; set; }
        public int Item_Id { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Item Item { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
