//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermeAvicole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseTransaction
    {
        public int PurchaseTransaction_Id { get; set; }
        public int Purchase_Id { get; set; }
        public int PurchaseItem_Id { get; set; }
        public int Quantity { get; set; }
        public decimal Item_Price { get; set; }
        public decimal Total { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual PurchaseItem PurchaseItem { get; set; }
    }
}
