//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermeAvicole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Store_Id { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int User_Id { get; set; }
        public string Store_Name { get; set; }
        public string Description { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
